name: "godot gut test"
on: push

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker test
        uses: croconut/godot-tester@master
        with:
          version: "3.4"
          release_type: "stable"
          test-dir: "res://tests"
